### ISSUE TITLE
cut a release

### ISSUE THREAD

**Issue by agarwal** [ocaml/opam2web#126]
The last release was very long ago. This is causing a variety of problems such as ocaml/ocaml.org#609. Before doing the release though, I'd suggest to be compatible with latest `cow`, and simplify the rather complex current constraint `"cow" {>= "0.6.0" & < "0.9.0" & (< "0.8.0" | > "0.8.0")}`.

**Comment by samoht** [comment]
This needs https://github.com/ocamllabs/opamfu/issues/13

I'll add an opam file to the repo though.

**Comment by samoht** [comment]
See https://github.com/ocaml/opam2web/pull/127
