### ISSUE TITLE
Add a link the (dev) manual into the "Documentation" menu

### ISSUE THREAD

**Issue by samoht** [ocaml/opam2web#130]
The dev manual link on the main page should be renamed to "manual" and the link should also be present in the "Documentation" top menu.

Also it seems that the documentation for the `.install` file disappeared from the tutorials.

**Comment by AltGr** [comment]
I was actually going to start breaking it in pieces to be integrated there directly in a more easily browsable format -- at least for the most useful parts like the `opam` file specification.

In its current form, the general index and many parts aren't really relevent to users/packagers (e.g. directory structure and format of internal files like `installed` or `pinned` under `~/.opam`) while others are extremely useful but not visible/accessible enough.

Indeed, there was some information on `.install` (still available in the old [wiki](https://github.com/ocaml/opam/wiki/Packaging#manually-installing-binaries-or-libaries)) that didn't fit in the scope of the newer [Packaging guide](https://opam.ocaml.org/doc/Packaging.html) and needs to be put back somewhere -- we kind of lost that middle step (between 'packaging 101' and detailed spec) when rewriting the docs.
