### ISSUE TITLE
Add links to OWS/Builder

### ISSUE THREAD

**Issue by lefessan** [ocaml/opam2web#136]
I think it would make sense to add links to the different services that have been built to improve the quality of the repository:
- OWS (http://ows.irill.org/)
- opam-builder (http://opam.ocamlpro.com/builder/)
- opam-archive (http://opam.ocamlpro.com/backup/)

I would add them in the "Contribute" section, and temporarily in the "News" section. Before doing such a PR, I would like to know the general feeling about such an addition (and maybe links to other related services that could be added at the same time).

**Comment by avsm** [comment]
Yes this would be great.  I would also add in the Docker multi-distro CI infrastructure, and perhaps @AltGr could describe the operation of the Camelus bot as well.

It would be good for each of these services to list out the URL of the live service, a link to how to replicate it (if available), the license that the source code is under, and a maintainer contact for the service.

**Comment by lefessan** [comment]
For the top page, it might be enough to give the link and a short overview, and have all these details available on the linked page ?

What's the link to the Docker multi-distro CI infrastructure ?

**Comment by avsm** [comment]
> What's the link to the Docker multi-distro CI infrastructure ?

https://github.com/avsm/ocaml-docker-infra/wiki -- i'm still documenting it and debugging it, will be a couple more days as each run spins up hundreds of containers so iteration takes a while.

**Comment by avsm** [comment]
None of the originally reported links work anymore, so closing this out.
