### ISSUE TITLE
How to use this with OPAM2

### ISSUE THREAD

**Issue by hongchangwu** [ocaml/opam2web#163]
The latest version of `opam2web` on opam uses `opam-lib`, whose latest version (1.3.1) is no longer compatible with opam 2.0 format. When I try to use `opam2web` built with this verison of `opam-lib` I get:

```
[ERROR] /home/vagrant/.opam reports a newer OPAM version, aborting.
```

How do I use `opam2web` with opam 2?

**Comment by AltGr** [comment]
Use the `2.0` branch :)

**Comment by AltGr** [comment]
(but indeed, it should be released on opam-repository)

**Comment by hongchangwu** [comment]
Thanks! That makes sense. Yeah it would be to get the 2.0 compatible version on the opam-repository.
