### ISSUE TITLE
New release for opam 2

### ISSUE THREAD

**Issue by hongchangwu** [ocaml/opam2web#164]
Related to #163. Currently one has to manually pin `opam2web` to the 2.0 branch to use it with opam 2.

**Comment by hongchangwu** [comment]
Anyone wants to take care of this? Should be a low-hanging fruit.

**Comment by avsm** [comment]
Now in https://github.com/ocaml/opam-repository/pull/14364

**Comment by hongchangwu** [comment]
@avsm thanks!
